# SPDX-License-Identifier: None
%YAML 1.2
---
$id: http://devicetree.org/schemas/Bindings/metag/meta.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#
version: 1

title: Meta Processor Binding

maintainers:
  - James Hogan <james.hogan@imgtec.com>
description: |+
  This binding specifies what properties must be available in the device tree
  representation of a Meta Processor Core, which is the root node in the tree.

             

properties:
  compatible:
    items:
      - enum:
          - toumaz,tz1090
          - img,meta
    minItems: 1
    maxItems: 1
    additionalItems: false
  '#address-cells':
    const: 0x1
  '#size-cells':
    const: 0x1
  interrupt-parent: {}
historical: |
  * Meta Processor Binding

  This binding specifies what properties must be available in the device tree
  representation of a Meta Processor Core, which is the root node in the tree.

  Required properties:

      - compatible: Specifies the compatibility list for the Meta processor.
        The type shall be <string> and the value shall include "img,meta".

  Optional properties:

      - clocks: Clock consumer specifiers as described in
        Documentation/devicetree/bindings/clock/clock-bindings.txt

      - clock-names: Clock consumer names as described in
        Documentation/devicetree/bindings/clock/clock-bindings.txt.

  Clocks are identified by name. Valid clocks are:

      - "core": The Meta core clock from which the Meta timers are derived.

  * Examples

  / {
  	compatible = "toumaz,tz1090", "img,meta";

  	clocks = <&meta_core_clk>;
  	clock-names = "core";
  };
